### ISSUE TITLE
Converting point from EPSG:3433 to Wgs84/EPSG:4326

### ISSUE THREAD

**Issue by framlingham** [wfletcher/EasyGIS.NET#116]
Dear W Fletcher, I'm trying to convert (1733200.924, 537594.0757) from NAD83 / Arkansas North (ftUS) (EPSG:3433) to WGS84, and it's not working. I've written a unit test to show the issue below. It outputs (∞, ∞), sadly. I tried to go direct to proj's commandline (cs2cs via OsGeo4W Shell), and for v8.0.1 and v9.2.1, this command `echo 1733200.92403 537594.0757 | cs2cs -f "%.7f" epsg:3433 epsg:4326` produces `35.8019722      -90.5806563 0.0000000` which looks good. I couldn't find a way on Windows to get the command line for 9.0 to test it. I tried having a go at updating the DLL to proj_9_2.dll, but I couldn't get it to load in `LoadLibrary` for whatever reason either. I'd really appreciate your help to get this conversion working.

P.S. I tried to write the unit test in a way that matched your existing unit test in `UnitTests/ProjectionTests.cs`
```
[Test]
public void TransformWgs84ToNad83ArkNorthFtRoundTrip()
{
	const double Delta = 0.0000001;
	ICRS wgs84 = CoordinateReferenceSystemFactory.Default.GetCRSById(CoordinateReferenceSystemFactory.Wgs84EpsgCode);
	// EPSG:3433  NAD83 / Arkansas North (ftUS)
	ICRS nad83ArkNFt = CoordinateReferenceSystemFactory.Default.GetCRSById(3433);

	using (ICoordinateTransformation transformation = CoordinateReferenceSystemFactory.Default.CreateCoordinateTrasformation(wgs84, nad83ArkNFt))
	{
		PointD wgs84Pt = new PointD(-90.5806563, 35.8019722);
		PointD arkansasPt = transformation.Transform(wgs84Pt);

		Assert.True(Math.Abs(arkansasPt.X - 1733200.9) < 0.1);
		Assert.True(Math.Abs(arkansasPt.Y - 537594.1) < 0.1);

		PointD roundTripPt = transformation.Transform(arkansasPt, TransformDirection.Inverse);

		Assert.True(Math.Abs(wgs84Pt.X - roundTripPt.X) < Delta);
		Assert.True(Math.Abs(wgs84Pt.Y - roundTripPt.Y) < Delta);
	}
}
```

**Comment by framlingham** [comment]
(we are using Xunit, so sorry if the Assert calls are a bit different)

**Comment by wfletcher** [comment]
Hi,
I've copied your unit test and it appears to be working when I run the test.
![image](https://github.com/wfletcher/EasyGIS.NET/assets/12992602/5f44c2bf-e234-40f8-96de-c91310761fba)

![image](https://github.com/wfletcher/EasyGIS.NET/assets/12992602/5724cde2-a33b-49ce-85bb-8b5692dd4908)

![image](https://github.com/wfletcher/EasyGIS.NET/assets/12992602/21f151df-4496-4d4d-8f7d-9a746a22de84)

I tried running this using x86 and x64 processor architectures and the tests passes in both. I also ran using .net framework and .Net6 and both are working.

Can you confirm that you are using the latest code.?I pushed some changes up about 2 weeks ago that included changes to EGIS.Projections that may have changed something here.

Another thing to check is that when proj is installed I think it may install a bunch of grid files into a directory. The native proj_9.0.dll may be attempting to use these to do the transformation. This page has links to environment variables that are used by proj to find these resource files. https://proj.org/en/9.2/usage/environmentvars.html#

The PC that I am running my tests on does not have proj installed, but I will test on another PC which does have proj installed to see if this makes a difference

**Comment by framlingham** [comment]
Thank you for testing it! I wrested with DLLs and got the 9.2 DLLs loaded and working, and it produces the same (∞, ∞) output as 9.0, so it's not that. I am working with EGIS code from late 2022, so I'll update before checking the proj paths (have installed some proj and OsGeo4W). We copied the project rather than use Nuget because there was something not getting included, maybe some DLLs? Actually, there's a warning I got that  you might have fixed already:
```
1>C:\Program Files\dotnet\sdk\7.0.400-preview.23225.8\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets(221,5): warning NU5100: The assembly 'content\geomutil_lib.dll' is not inside the 'lib' folder and hence it won't be added as a reference when the package is installed into a project. Move it into the 'lib' folder if it needs to be referenced.
1>C:\Program Files\dotnet\sdk\7.0.400-preview.23225.8\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets(221,5): warning NU5100: The assembly 'contentFiles\any\net48\geomutil_lib.dll' is not inside the 'lib' folder and hence it won't be added as a reference when the package is installed into a project. Move it into the 'lib' folder if it needs to be referenced.
1>C:\Program Files\dotnet\sdk\7.0.400-preview.23225.8\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets(221,5): warning NU5100: The assembly 'content\geomutil_libx64.dll' is not inside the 'lib' folder and hence it won't be added as a reference when the package is installed into a project. Move it into the 'lib' folder if it needs to be referenced.
1>C:\Program Files\dotnet\sdk\7.0.400-preview.23225.8\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets(221,5): warning NU5100: The assembly 'contentFiles\any\net48\geomutil_libx64.dll' is not inside the 'lib' folder and hence it won't be added as a reference when the package is installed into a project. Move it into the 'lib' folder if it needs to be referenced.
1>The package EGIS.ShapeFileLib.4.8.5 is missing a readme. Go to https://aka.ms/nuget/authoring-best-practices/readme to learn why package readmes are imp
```

**Comment by framlingham** [comment]
After updating the code, it pretty much fixed it. I might still have some alternative PROJ grid files being loaded though, because the `arkansasPt.Y` was 53759**2.9**, not 53759**4.1**. Such a difference may be wrong, but it's a lot better than before (and I'm happy to live with that), so thanks again Winston!
